default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: ls-auth-ui_development


test:
  <<: *default
  database: ls-auth-ui_test

production:
  encoding: unicode
  pool: 5
  url: <%= ENV["LS_DATABASE_URI"] %>
